notifications:
  email: false
language: cpp
os:
  - linux
  # - osx
install:
  - sudo apt-get update && sudo apt-get -y install g++-5 libhdf5-serial-dev
  # - brew update && brew install libhdf5
compiler: gcc
script:
  - make
  - make test
