notifications:
  email: false
language: cpp
os:
  - linux
  # - osx
sudo: false
# install:
#   - sudo apt-get update && sudo apt-get -y install g++-4.9 libhdf5-serial-dev
#   # - brew update && brew install libhdf5
addons:
  apt:
    packages:
      - g++-4.8
      - libhdf5-serial-dev
compiler:
  # - clang
  - gcc
script:
  - make
  - make test
