notifications:
  email: false
os:
  - linux   # This is currently Ubuntu 12.04 LTS
  - osx
sudo: false
addons:
 apt:
   packages:
     - lcov
     # - libhdf5-serial-dev   # This lacks the HDF5 C++ bindings
     - libopenmpi-dev
     - openmpi-bin
     - python-numpy
     - swig
before_install:
  - |
    if [ `uname` = Darwin ]; then
      brew update
      brew install homebrew/science/hdf5
      brew install lcov
      brew install open-mpi
      brew install swig
    fi
  - |
    if [ `uname` = Linux ]; then
      export HDF5_DIR="$HOME/hdf5-1.8.17"
      (
        mkdir external
        cd external
        wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.17.tar.bz2
        tar xjf hdf5-1.8.17.tar.bz2
        mkdir hdf5-1.8.17-build
        cd hdf5-1.8.17-build
        `pwd`/../hdf5-1.8.17/configure --prefix="$HDF5_DIR" --enable-cxx
        make -j2
        make -j2 install
      )
      export PATH="$HDF5_DIR/bin:$PATH"
    fi
  - pip install --user codecov
  - gem install coveralls-lcov
  - h5ls --version
  - mpirun --version
  - lcov --version
language: cpp
compiler:
  - clang
  - gcc
script:
  - make -j2 COVERAGE=1 CXX="$CXX" HDF5_DIR="$HDF5_DIR" MPI_NAME=openmpi MPI_LIBS=-lmpi
  - make -j2 test
  - ./sio-example && ./sio-list example.s5
  - python setup.py install
  - ./python-example.py && ./sio-list python-example.s5
  # - ./julia-example.jl && ./list julia-example.s5
after_success:
  - make -j2 coverage
  - codecov
  - coveralls-lcov coverage.info
