notifications:
  email: false
os:
  - linux   # This is currently Ubuntu 12.04 LTS
  - osx
sudo: false
addons:
  apt:
    packages:
      - libhdf5-serial-dev
before_install:
  - [ `uname` = Darwin ] && brew update
  - [ `uname` = Darwin ] && brew install libhdf5
language: cpp
compiler:
  - clang
  - gcc
script:
  - make
  - make test
