notifications:
  email: false
os:
  - linux   # This is currently Ubuntu 12.04 LTS
  - osx
sudo: false
addons:
  apt:
    packages:
      - libhdf5-serial-dev
before_install:
  - if [ `uname` = Darwin ]; then brew update; fi
  - if [ `uname` = Darwin ]; then brew install homebrew/science/libhdf5; fi
language: cpp
compiler:
  - clang
  - gcc
script:
  - make
  - make test
